version: '3'
services:
    proxy:
        image: nginx:latest
        volumes:
            - "./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./nginx-proxy/ssl/certs:/etc/nginx/ssl:ro"
            - "./nginx-proxy/html:/usr/share/nginx/html:ro"
            - "/home/ubuntu/nginx:/var/log/nginx"
        restart: always
        ports:
            - "80:80"
            - "443:443"