version: '2'

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:   
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/db/phloxdb/portainer/data