version: '2'
services:
    wsindex-elasticsearch:
        container_name: wsindex-elasticsearch
        image: elasticsearch:2.4.1
        volumes:
            - ../../wsdata/elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch-conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    wisestepdb-cassandra:
        container_name: wisestepdb-cassandra
        image: cassandra:3.9
        volumes:
            - ../../wsdata/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    # wisestepdb-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: wisestepdb-cassandra-migration
    #     links:
    #         - wisestepdb-cassandra
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
