version: '2'
services:
    cassandra-one:
        image: cassandra:3.9
        volumes:
            - ./db/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            - CASSANDRA_CLUSTER_NAME='alpha-cluster'
            - CASSANDRA_NUM_TOKENS=256
            # - CASSANDRA_SEEDS=18.220.240.109, 52.14.135.228
            # - CASSANDRA_LISTEN_ADDRESS=18.220.240.109
            - CASSANDRA_BROADCAST_ADDRESS=18.220.240.109
            # - CASSANDRA_RPC_ADDRESS=52.14.135.228
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    