version: '2'
services:
  elasticsearch2:
    image: elasticsearch:2.4.1
    container_name: elasticsearch-two
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=54.169.122.211:9300" # replace the IP 
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # mem_limit: 1g
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
#     networks:
#       - esnet
# volumes:
#   esdata1:
#     driver: local
#   esdata2:
#     driver: local

# networks:
#   esnet: